# These are supported funding model platforms

# GitHub Sponsors - Enable via repository settings: https://github.com/sponsors
# github: [your-username]

# Alternative funding platforms (uncomment and configure when needed)
# patreon: your-username
# open_collective: your-slug
# ko_fi: your-username
# tidelift: platform-name/package-name
# custom: ['https://paypal.me/your-username', 'https://buymeacoffee.com/your-username']
