# These are supported funding model platforms

github: [your-username]
patreon: # Replace with your Patreon username
open_collective: # Replace with your OpenCollective username
ko_fi: # Replace with your Ko-fi username
tidelift: # Replace with Tidelift platform name/package
custom: ['https://paypal.me/yourusername'] # Replace with your custom donation link
