//! Fill utilities - fill, fill_with

/// Fills a slice with a value.
///
/// # Examples
///
/// ```rust
/// use abseil::absl_algorithm::fill;
///
/// let mut data = [0; 5];
/// fill(&mut data, 42);
/// assert_eq!(data, [42; 5]);
/// ```
#[inline]
pub fn fill<T: Copy>(slice: &mut [T], value: T) {
    for item in slice.iter_mut() {
        *item = value;
    }
}

/// Fills a slice with values generated by a function.
///
/// # Examples
///
/// ```rust
/// use abseil::absl_algorithm::fill_with;
///
/// let mut data = [0; 5];
/// let mut i = 0;
/// fill_with(&mut data, || {
///     let val = i * i;
///     i += 1;
///     val
/// });
/// assert_eq!(data, [0, 1, 4, 9, 16]);
/// ```
#[inline]
pub fn fill_with<T, F: FnMut() -> T>(slice: &mut [T], mut f: F) {
    for item in slice.iter_mut() {
        *item = f();
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_fill() {
        let mut data = [0; 5];
        fill(&mut data, 42);
        assert_eq!(data, [42; 5]);
    }

    #[test]
    fn test_fill_with() {
        let mut data = [0; 5];
        let mut i = 0;
        fill_with(&mut data, || {
            let val = i * i;
            i += 1;
            val
        });
        assert_eq!(data, [0, 1, 4, 9, 16]);
    }
}
